#!/bin/bash

set -eo pipefail

containerName="$1"

docker run --rm \
           --link=$containerName:app \
           tutum/curl \
           bash \
           -c \
           "curl http://\$APP_PORT_80_TCP_ADDR:\$APP_PORT_80_TCP_PORT/health"
